# [START runtime]
runtime: nodejs8
handlers:
  - url: /
    static_files: dist/my-resume/index.html
    upload: dist/my-resume/index.html
  - url: /
    static_dir: dist/my-resume
manual_scaling:
  instances: 1
# [END runtime]
